# models/sp001/staging/sources.yml

version: 2

sources:
  - name: sp001             # 這是 BigQuery 中的 dataset 名稱
    database: daily-report-401707   # GCP專案名稱
    schema: sp001            # =dataset 就是 schema
    tables:
      - name: operation
      - name: recharge