version: 2

models:
  - name: mrt_user_recharge_segmented
    description: >
      使用者儲值行為分群主表，整合儲值摘要、付款偏好與裝置偏好，
      並加入商業語意標籤（如金額層級、活躍度、生命周期等）。

    columns:
      - name: user_id
        description: 使用者 ID（主鍵）
        tests: [not_null, unique]

      - name: first_recharge_date
        description: 首次儲值日期
        tests: [not_null]

      - name: latest_recharge_date
        description: 最近儲值日期
        tests: [not_null]

      - name: recharge_lifetime_days
        description: 儲值生命週期（天數）

      - name: total_recharge_amount
        description: 累積儲值金額

      - name: total_recharge_times
        description: 累積儲值筆數

      - name: avg_recharge_amount
        description: 平均每筆儲值金額

      - name: max_recharge_amount
        description: 歷來最大單筆儲值金額

      - name: preferred_payment_type
        description: 使用者最常使用的付款方式

      - name: payment_type_count
        description: 使用者使用過幾種付款方式

      - name: preferred_payment_usage_count
        description: 最常使用付款方式的次數

      - name: preferred_payment_usage_ratio
        description: 該付款方式佔所有儲值次數的比例

      - name: preferred_device_type
        description: 最常使用的裝置類型

      - name: device_type_count
        description: 使用過幾種裝置類型

      - name: recharge_tier
        description: 儲值金額層級標籤
        tests:
          - accepted_values:
              values: ['low', 'medium', 'high']

      - name: activity_level
        description: 使用者活躍程度標籤
        tests:
          - accepted_values:
              values: ['inactive', 'active', 'very_active']

      - name: lifecycle_stage
        description: 使用者儲值生命週期標籤
        tests:
          - accepted_values:
              values: ['new', 'retained', 'dormant']

      - name: is_payment_loyal
        description: 是否只使用一種付款方式（true = 忠誠用戶）
        tests: [not_null]

