name: "sp01_dbt"
version: "1.0.0"
profile: "default"
config-version: 2

seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"
    - "logs"

models:
    sp01_dbt:
        staging:
            materialized: view
        intermediate:
            materialized: table
        mart:
            materialized: table

vars:
    data_start_date: "2024-01-01"

packages:
    - package: dbt-labs/dbt_utils
      version: 1.1.1

require-dbt-version: ">=1.7.0"