version: 2

models:
  - name: int_user_device_pref
    description: >
      每位使用者在所有儲值記錄中最常使用的裝置類型（如 mobile、web、tablet）。
      作為後續使用者輪廓與裝置行為分析的中繼資料表。

    columns:
      - name: user_id
        description: 使用者 ID（主鍵）
        tests:
          - not_null
          - unique

      - name: preferred_device_type
        description: 使用者最常使用的裝置類型（如 mobile、web）
        tests:
          - not_null

      - name: usage_count
        description: 該裝置類型被該使用者使用的次數
        tests:
          - not_null
