name: sp001
version: '1.0.0'
profile: sp001
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  sp001:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    mart:
      +materialized: table

vars:
  data_start_date: "2023-01-01"

packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1

require-dbt-version: ">=1.7.0"  